# Generated by Django 5.1.11 on 2025-10-01 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_description_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled')], default='scheduled', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_events_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupEventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rsvp', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined'), ('changed', 'changed')], default='pending', max_length=16)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_version', models.PositiveIntegerField(blank=True, null=True)),
                ('needs_response', models.BooleanField(default=False)),
                ('group_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.groupevent')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_event_attendance', to='api.membership')),
                ('personal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_group_attendance', to='api.event')),
            ],
            options={
                'unique_together': {('group_event', 'membership')},
            },
        ),
    ]
