services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - backend-static:/app/static
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend-static:/app/static
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  backend-static:
